### ISSUE TITLE
Subresource behavior

### ISSUE THREAD

**Issue by annevk** [dadrian/https-upgrade#3]
I should probably make time to read the Fetch PR, but reading the explainer makes me confused about subresources. In particular it states

> The browser may choose to upgrade active and passive mixed content in addition to upgrading links.

but then also states

> HTTPS Upgrade only affects main-frame navigations. Subresource upgrades are controlled by the user agent's policies on mixed content (i.e. autoupgrading passive mixed content). A page that is upgraded to HTTPS should follow existing policies for mixed content.

How does that work? And also, we no longer have active and passive mixed content. They're called Blockable and Upgradeable.

**Comment by christhompson** [comment]
The way we are thinking of this is that HTTPS Upgrades depends on MIX Level 2 (with upgrades or blocking for all subresources). Kind of relatedly, in Chrome we rely on our "mixed forms" interstitial warning to handle the cases of a POST form submission from a secure page to an insecure one, as HTTPS Upgrades only handled idempotent requests (due to the fallback behavior). The wording here was to try to call out that HTTPS Upgrades and mixed content upgrading/blocking are complementary but non-overlapping -- we can definitely tweak this wording if it is confusing or unclear.

We'll update the text to prefer Upgradable/Blockable terminology also.

**Comment by annevk** [comment]
What would be a case where a browser would choose to upgrade blockable (the new active as I understand it) mixed content?

**Comment by dadrian** [comment]
I don't know of any proposals at this time for browsers to upgrade Blockable mixed content. We've tossed the idea around internally but never decided to do anything with it. In terms of how this relates to HTTPS Upgrades, I think Chris gave a more complete answer on the WICG Proposal issue: https://github.com/WICG/proposals/issues/63#issuecomment-1599449396

**Comment by annevk** [comment]
Okay, then remove that text from the explainer?

**Comment by dadrian** [comment]
Deleted that paragraph, and updated the "Subresources" bullet to use the new terminology.

> Subresources: HTTPS Upgrade only affects main-frame navigations. Subresource upgrades are controlled by the user agent's policies on Blockable and Upgradeable mixed content (i.e. autoupgrading Upgradeable mixed content). A page that is upgraded to HTTPS should follow existing policies for mixed content.

**Comment by annevk** [comment]
Thanks. From my perspective this can be closed, but I'll leave it open in case you wanted to do something else.
